version: 1.0.{build}
environment:
  nodejs_version: "4.2.2"
  GITHUB_KEY:
    secure: eZcSozzDKzRJhSoXL7LS9w1jqFLdkiRT4H57JoWGpKj/kS6NC/DP3ColwKkvSeFn
  SIGN_CERT_PASS:
    secure: UEVPxVtsn5UnAi3PhhkUSA==
  GPMDP_LASTFM_API_KEY:
    secure: fUSv2FRL2zURkC40MqqZct2FCODoi1ep1W1wtPAEqf3PzTvOfKRNDJdC721w8NM7
  GPMDP_LASTFM_API_SECRET:
    secure: 9XmaZrxycp9P4P53I3gNPhlMv299Q5NSE2LaKxw7p6zlO6ZdDhrotByHb0zlqEHW


platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm upgrade

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

build_script:
- cmd: npm run make:win

artifacts:
  - path: 'dist\win32\Google Play Music Desktop PlayerSetup.exe'
