version: 1.0.{build}
environment:
  nodejs_version: "6.3.0"
  GITHUB_KEY:
    secure: eZcSozzDKzRJhSoXL7LS9w1jqFLdkiRT4H57JoWGpKj/kS6NC/DP3ColwKkvSeFn
  SIGN_CERT_PASS:
    secure: UEVPxVtsn5UnAi3PhhkUSA==
  GPMDP_LASTFM_API_KEY:
    secure: t4Ka6QT10/i0FMX4cVi4BaNeGKfi76T/iEKZ3PEsnUPrQ2lK6cmlGSA01NfHvUze
  GPMDP_LASTFM_API_SECRET:
    secure: RIfJtcbYwHBG7uGI8TQS9JzO37zPNuyO3yPPayVKb8vVISfxrFXH4rYT9dzmGaAx
  GPMDP_SENTRY_DSN:
    secure: SOdAq6QgqVupAJIbh7LIUDa3hv5cgjR5bZD4u2x1/4ErWjwzoYjZwTQoaNaPSwZ5cx7bda0ExE5oBjoJJSmXki0yjKMHRur172h2ysk4FHYb7S2zW7lHTBCiDXOryVHS
  GOOGLE_MUSIC_JS_EMAIL:
    secure: UtCUPcatc43rCKYKuQUl+Q==
  GOOGLE_MUSIC_JS_PASSWORD:
    secure: ysdUmqSIrW+4OE1sRvLp+g==
  BONJOUR_SDK_HOME: 'C:\\Program Files\\Bonjour SDK'
  GPMDP_DONT_BUILD_DELTAS: 'true'

branches:
  except:
  - website

os: Visual Studio 2013
platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: Install-Product node $env:nodejs_version

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
- cmd: node --version

artifacts:
  - path: 'dist\installers\win32\Google Play Music Desktop PlayerSetup.exe'
